#!/bin/bash

docker image pull php:8.2-apache-bullseye
docker image pull php:8.1-apache-bullseye
docker image pull php:8.0-apache-bullseye
docker image pull php:7.4-apache-buster

VERSION="9.5-apache"
docker build -t neffets/drupal:$VERSION -t neffets/drupal:latest -f 9.5/php8.1/apache-bullseye/Dockerfile 9.5/php8.1/apache-bullseye/
docker push neffets/drupal:$VERSION

VERSION="10.0-apache"
docker build -t neffets/drupal:$VERSION -f 10.0/php8.2/apache-bullseye/Dockerfile 10.0/php8.2/apache-bullseye/
docker push neffets/drupal:$VERSION

VERSION="9.4-apache"
docker build -t neffets/drupal:$VERSION -f 9.4/php8.1/apache-bullseye/Dockerfile 9.4/php8.1/apache-bullseye/
docker push neffets/drupal:$VERSION
docker push neffets/drupal:latest

VERSION="7-apache"
docker build --no-cache -t neffets/drupal:$VERSION -f 7/php8.0/apache-bullseye/Dockerfile 7/php8.0/apache-bullseye/
docker push neffets/drupal:$VERSION

VERSION="6-apache"
docker build --no-cache -t neffets/drupal:$VERSION -f 6/php7.4/apache-buster/Dockerfile 6/php7.4/apache-buster/
docker push neffets/drupal:$VERSION

