#!/bin/sh
set -e

### INIT
if [ "x${DRUPAL_SUBDIR}" != "x" ]; then
	if [ -L "/etc/apache2/sites-enabled/000-default.conf" ]; then
		/bin/rm "/etc/apache2/sites-enabled/000-default.conf"
		cat >/etc/apache2/sites-enabled/000-default.conf <<EOT
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog \${APACHE_LOG_DIR}/error.log
	CustomLog \${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

	<Directory "/var/www/html">
		RewriteEngine on
		RewriteBase ${DRUPAL_SUBDIR}
		RewriteCond %{REQUEST_URI} !=${DRUPAL_SUBDIR}/index.php
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_URI} !=/favicon.ico
		RewriteCond %{REQUEST_URI} !^/(_|\.)
		RewriteRule ^(.*)$ index.php?q=\$1 [L,QSA]
		<FilesMatch "\.(engine|inc|info|install|module|profile|test|po|sh|.*sql|theme|tpl(\.php)?|xtmpl|svn-base)$|^(code-style\.pl|Entries.*|Repository|Root|Tag|Template|all-wcprops|entries|format)$">
			Order allow,deny
			Deny From All
		</FilesMatch>
	</Directory>
	Alias ${DRUPAL_SUBDIR} /var/www/html/
</VirtualHost>
EOT
	fi
fi
if [ "x${APACHE_UID}" != "x" -a "x${APACHE_GID}" != "x" ]; then
	perl -pi -e 's#^www-data:x:\d+:\d+:#www-data:x:'${APACHE_UID}':'${APACHE_GID}':#' /etc/passwd
	perl -pi -e 's#^www-data:x:\d+:#www-data:x:'${APACHE_GID}':#' /etc/group
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
