#!/bin/bash

# Step 1 - add optional Composer-Modules
if [ "$DRUPAL_COMPOSER_MODULES" != "" ]; then
(
cd /opt/drupal
for MOD in $DRUPAL_COMPOSER_MODULES;
do
    composer require "$MOD"
done
)
fi

# LAST start normal apache2-foreground
exec /usr/local/bin/apache2-foreground "$@"
